### ISSUE TITLE
Social Authentication - When trying google authentication, it says "Hi Harsh2", why is my name "Harsh2"?

### ISSUE THREAD

**Issue by dexter1691** [batra-mlp-lab/CloudCV#14] opened 2015-06-23 16:54 UTC

**Comment by deshraj** [comment] 2015-09-21 19:45
The issue is fixed now. This problem was arising due to the default settings that were provided by django-allauth. Now, the login method has been changed to username/email and the problem has been fixed successfully. For a single user, there is a single username only.

**Closed as completed by deshraj** 2015-09-21 19:45 UTC
Labels: social_auth
